from database import db
from datetime import datetime


class Topic(db.Model):
    """
    Represents a learning topic that a user wants to study.
    Each topic has a curriculum generated by AI.
    """
    __tablename__ = 'topics'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(200), nullable=False)
    description = db.Column(db.Text, nullable=False)
    level = db.Column(db.String(50), nullable=False)  # beginner, intermediate, advanced
    focus_areas = db.Column(db.Text)  # Specific areas the user wants to focus on
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationship to curriculum sections
    sections = db.relationship('CurriculumSection', backref='topic', lazy=True, cascade='all, delete-orphan')

    def to_dict(self):
        """Convert topic to dictionary for JSON serialization"""
        return {
            'id': self.id,
            'name': self.name,
            'description': self.description,
            'level': self.level,
            'focus_areas': self.focus_areas,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
            'sections_count': len(self.sections)
        }
